#ifndef COMMON_RESET_CONTRACT_H
#define COMMON_RESET_CONTRACT_H

typedef enum
{
    RESET_REASON_UNKNOWN = 0,
    RESET_REASON_IWDG,
    RESET_REASON_SOFTWARE,
    RESET_REASON_POWER_ON,
    RESET_REASON_EXTERNAL,
    RESET_REASON_LOW_POWER
} common_reset_reason_t;

#endif /* COMMON_RESET_CONTRACT_H */
