CC := gcc
CFLAGS := -std=c99 -Wall -Wextra -Werror -g -O0
INCLUDES := -Itask_queue_stubs -I../Tasks/inc -Iunity
TARGET ?= /tmp/industrial_task_queues_test
SOURCES := ../Tasks/src/task_queues.c unity/unity.c test_task_queues.c

.PHONY: test
test:
	$(CC) $(CFLAGS) $(INCLUDES) $(SOURCES) -o $(TARGET)
	$(TARGET)
